# Generated by Django 3.0 on 2023-07-04 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230629_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='components',
            old_name='count',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное значение 1')], verbose_name='Время приготовления'),
        ),
    ]
